language: php

php:
    - 5.3
#    - 5.4

env:
    - WP_VERSION=master WP_MULTISITE=1
#    - WP_VERSION=master WP_MULTISITE=0

before_script:
    - pear install --alldeps PHP_CodeSniffer
#    - pear config-set auto_discover 1
#    - pear install --alldeps pear.phpqatools.org/phpqatools
    - phpenv rehash
    - git clone git://github.com/mrchrisadams/WordPress-Coding-Standards.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress
#    - export WP_TESTS_DIR=/tmp/wordpress-tests/
#    - bash bin/install-wp-tests.sh wordpress_test root '' $WP_VERSION 
    - export PWD=`pwd`

script:
#    - phpcs --standard=${PWD}/phpcs.ruleset.xml .
    - phpcs --standard=WordPress .
#    - phpunit

notifications:
    email:
        on_failure: change
