language: php

#    - 5.4
php:
    - 5.3

#    - WP_VERSION=master WP_MULTISITE=0
#    - WP_VERSION=3.5.2 WP_MULTISITE=0
#    - WP_VERSION=3.5.2 WP_MULTISITE=1
env:
    - WP_VERSION=master WP_MULTISITE=1

#    - pear install --alldeps pear.phpqatools.org/phpqatools
before_script:
    - pear config-set auto_discover 1
    - pear install --alldeps PHP_CodeSniffer
    - phpenv rehash
    - git clone git://github.com/mrchrisadams/WordPress-Coding-Standards.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress
    - export WP_TESTS_DIR=/tmp/wordpress-tests/
    - bash bin/install-wp-tests.sh wordpress_test root '' $WP_VERSION 

script:
    - phpcs --standard=/home/travis/build/michael-cannon/testimonials-widget/phpcs.ruleset.xml .
    - phpunit
