language: php

#    - 5.4
php:
    - 5.3

#    - WP_VERSION=master WP_MULTISITE=0
#    - WP_VERSION=3.5.2 WP_MULTISITE=0
#    - WP_VERSION=3.5.2 WP_MULTISITE=1
env:
    - WP_VERSION=master WP_MULTISITE=1

#    - export WP_TESTS_DIR=/tmp/wordpress-tests/
#    - bash bin/install-wp-tests.sh wordpress_test root '' $WP_VERSION 
#    - pear install --alldeps pear.phpqatools.org/phpqatools
#    - pear config-set auto_discover 1
before_script:
    - pear install --alldeps PHP_CodeSniffer
    - phpenv rehash
    - git clone git://github.com/mrchrisadams/WordPress-Coding-Standards.git $(pear config-get php_dir)/PHP/CodeSniffer/Standards/WordPress

#    - phpunit
#    /home/travis/build/michael-cannon/testimonials-widget
script:
    - phpcs --standard=`pwd`/phpcs.ruleset.xml .
